# Generated by Django 2.0.5 on 2018-05-04 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('PR', 'Producto'), ('SR', 'Servicio')], max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('is_variation', models.BooleanField()),
                ('code', models.CharField(max_length=50)),
                ('is_complement', models.BooleanField()),
                ('is_deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_visibility', models.FloatField()),
                ('price', models.FloatField()),
                ('price_offer', models.FloatField()),
                ('offer_day_from', models.DateTimeField()),
                ('offer_day_to', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('sku', models.FloatField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalogue.Product')),
            ],
        ),
    ]
